### PR TITLE
remove use of select() that does not work under windows

### PR DESCRIPTION
**Pull request by EddieParis**
using pySerial timeout instead.

I also converted all tabs to spaces (pep-8 recommendation)

reworked bulk transfer

### CODE REVIEW

**Comment by audiohacked** [comment]
I've taken a look at your pull request and I much rather see you "overload" timeout with an implementation that works on Windows. Fixing *my* formatting issues is fine and nice of you to do. I may have not communicated why there's timeout() in the code. It's for a pause between sending and receiving  data from the BusPirate, and was part of the protocol requirements for the firmware version on my BusPirate.

**Comment by EddieParis** [comment]
If you look closely the timeout function is no more used, and I thought about removing it from bbio.
Any call to it has been replaced by a call to response() where possible. Have a look to the bulk transfer method that I rewrote to get the result after each transmission.
If the data is not ready, pyserial will hold for maximum 1 second waiting incoming byte(s). This is exactly as in your implementation, but using pyserial timeout instead of explicit select() with timeout (pyserial also uses a select, but they got the fd of serial port hence having no issues on Windows).

I tested i2c and spi, it works fine with my bp v3 and latest firmware, on Windows and Linux and with Python 2.7 and 3.x

**Comment by audiohacked** [comment]
I'm not sure I understand how pyserial's timeout works. Could you explain why we are switching to it and not just fixing the windows-select() problem? How do we ensure we don't de-sync communication? How is write-wait-read different from write-read communication loop?

**Comment by audiohacked** [comment]
After some reading of pyserial's docs and other examples. I believe pyserial timeout has to do with communication buffers and not the actual transmission. I'd prefer if you send a new pull request and branch that only changes select() to the new/proper time.sleep() and fixes for pep-8

**Comment by audiohacked** [comment]
Here's a few reasons from the creator of why timeout():
http://dangerousprototypes.com/forum/viewtopic.php?f=4&t=3180&p=31350&hilit=binary+mode+sleep#p31350

http://dangerousprototypes.com/forum/viewtopic.php?f=28&t=2344&p=22240&hilit=binary+mode+sleep#p22240

**Comment by EddieParis** [comment]
Obviously pyserial timeouts are dealing with input buffers. There is no way to regulate the output stream in pyserial. 
But the bytes are sent one by one, and after each send we wait for the bp answer. So there is no worry about sending the bytes too fast. This is the only way to do so because there is no hardware handshake on the bp serial line. 

My implementation is equivalent to what you did before, but it does not use an explicit call to select(). 

Again look at the bulk_transfer. In your version you are sending one byte and calling timeout. It waits for x seconds maximum to get a byte on serial line which is put in pyserial buffer and so on until last byte. Then you gather all inputs by reading at once the input buffer. 
In my version, instead of calling timeout, I actually read the answer. Pyserial will wait for it for a maximum of 1 second (as you're timeout function would have done). 

Same effect but arranged differently. 

And to complete on the select() you used as a timeout, it actually waits for any file related event for a maximum of x seconds, being equivalent to pyserial.read(1)

Do you get my point ?

**Pull request closed without merging**
